# Configurações do Servidor
server.port=8080

# Nome da Aplicação
spring.application.name=devmeet-hub-api

# Configurações do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/devmeet_db
spring.datasource.username=postgres
spring.datasource.password=victor
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações JPA e Hibernate
# 'update' atualiza as colunas da tabela mantendo os dados. Em produção, use ferramentas de Migração (ex: Flyway).
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ViaCEP API Configuration
viacep.api.url=https://viacep.com.br/ws
